// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActivateUserReducer from "../activate_user_reducer";
import AddBookReducer from "../add_book_reducer";
import AddBranchReducer from "../add_branch_reducer";
import AddRatingReducer from "../add_rating_reducer";
import AddUserReducer from "../add_user_reducer";
import CheckinBookReducer from "../checkin_book_reducer";
import CheckoutBookReducer from "../checkout_book_reducer";
import CompleteAiGenerationReducer from "../complete_ai_generation_reducer";
import CreateNotificationReducer from "../create_notification_reducer";
import DeleteBookReducer from "../delete_book_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import RegisterAiGenerationReducer from "../register_ai_generation_reducer";
import RenewBookReducer from "../renew_book_reducer";
import SuspendUserReducer from "../suspend_user_reducer";
import UpdateBookReducer from "../update_book_reducer";
import UpdateBranchReducer from "../update_branch_reducer";
import UpdateUserReducer from "../update_user_reducer";

export type ActivateUserParams = __Infer<typeof ActivateUserReducer>;
export type AddBookParams = __Infer<typeof AddBookReducer>;
export type AddBranchParams = __Infer<typeof AddBranchReducer>;
export type AddRatingParams = __Infer<typeof AddRatingReducer>;
export type AddUserParams = __Infer<typeof AddUserReducer>;
export type CheckinBookParams = __Infer<typeof CheckinBookReducer>;
export type CheckoutBookParams = __Infer<typeof CheckoutBookReducer>;
export type CompleteAiGenerationParams = __Infer<
  typeof CompleteAiGenerationReducer
>;
export type CreateNotificationParams = __Infer<
  typeof CreateNotificationReducer
>;
export type DeleteBookParams = __Infer<typeof DeleteBookReducer>;
export type MarkNotificationReadParams = __Infer<
  typeof MarkNotificationReadReducer
>;
export type RegisterAiGenerationParams = __Infer<
  typeof RegisterAiGenerationReducer
>;
export type RenewBookParams = __Infer<typeof RenewBookReducer>;
export type SuspendUserParams = __Infer<typeof SuspendUserReducer>;
export type UpdateBookParams = __Infer<typeof UpdateBookReducer>;
export type UpdateBranchParams = __Infer<typeof UpdateBranchReducer>;
export type UpdateUserParams = __Infer<typeof UpdateUserReducer>;
