// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import { UserRole, MembershipType } from "./types";

export default {
  clerkId: __t.string(),
  name: __t.string(),
  email: __t.string(),
  get role() {
    return UserRole;
  },
  phone: __t.option(__t.string()),
  get membershipType() {
    return MembershipType;
  },
};
