// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AiGenerationStatus,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  prompt: __t.string(),
  resultBookId: __t.option(__t.string()).name("result_book_id"),
  get status() {
    return AiGenerationStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
});
