// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { BookCategory, BookFormat, BookStatus } from "./types";

export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  author: __t.string(),
  isbn: __t.string(),
  get category() {
    return BookCategory;
  },
  publishedDate: __t.string().name("published_date"),
  publisher: __t.string(),
  totalCopies: __t.i32().name("total_copies"),
  availableCopies: __t.i32().name("available_copies"),
  get status() {
    return BookStatus;
  },
  coverUrl: __t.option(__t.string()).name("cover_url"),
  description: __t.option(__t.string()),
  location: __t.string(),
  branchId: __t.string().name("branch_id"),
  get format() {
    return __t.array(BookFormat);
  },
  pages: __t.option(__t.i32()),
  language: __t.option(__t.string()),
  edition: __t.option(__t.string()),
  pdfData: __t.option(__t.string()).name("pdf_data"),
  coverData: __t.option(__t.string()).name("cover_data"),
  rating: __t.f64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
