// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { BorrowStatus } from "./types";

export default __t.row({
  id: __t.string().primaryKey(),
  bookId: __t.string().name("book_id"),
  userId: __t.string().name("user_id"),
  borrowDate: __t.string().name("borrow_date"),
  dueDate: __t.string().name("due_date"),
  returnDate: __t.option(__t.string()).name("return_date"),
  get status() {
    return BorrowStatus;
  },
  branchId: __t.string().name("branch_id"),
  fine: __t.option(__t.f64()),
  renewCount: __t.i32().name("renew_count"),
});
