// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BranchStatus,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  address: __t.string(),
  city: __t.string(),
  phone: __t.string(),
  email: __t.string(),
  manager: __t.string(),
  totalBooks: __t.i32().name("total_books"),
  totalMembers: __t.i32().name("total_members"),
  get status() {
    return BranchStatus;
  },
  openHours: __t.string().name("open_hours"),
});
