// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { UserRole, MembershipType, UserStatus } from "./types";

export default __t.row({
  id: __t.string().primaryKey(),
  clerkId: __t.string().name("clerk_id"),
  name: __t.string(),
  email: __t.string(),
  get role() {
    return UserRole;
  },
  phone: __t.option(__t.string()),
  address: __t.option(__t.string()),
  avatar: __t.option(__t.string()),
  memberSince: __t.string().name("member_since"),
  get membershipType() {
    return MembershipType.name("membership_type");
  },
  borrowLimit: __t.i32().name("borrow_limit"),
  bio: __t.option(__t.string()),
  registerNumber: __t.option(__t.string()).name("register_number"),
  department: __t.option(__t.string()),
  get status() {
    return UserStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
});
