// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import { NotificationType } from "./types";

export default __t.row({
  id: __t.string().primaryKey(),
  userId: __t.string().name("user_id"),
  get notificationType() {
    return NotificationType.name("notification_type");
  },
  title: __t.string(),
  message: __t.string(),
  date: __t.string(),
  read: __t.bool(),
});
