// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AiGeneration = __t.object("AiGeneration", {
  id: __t.string(),
  userId: __t.string(),
  prompt: __t.string(),
  resultBookId: __t.option(__t.string()),
  get status() {
    return AiGenerationStatus;
  },
  createdAt: __t.timestamp(),
});
export type AiGeneration = __Infer<typeof AiGeneration>;

// The tagged union or sum type for the algebraic type `AiGenerationStatus`.
export const AiGenerationStatus = __t.enum("AiGenerationStatus", {
  Pending: __t.unit(),
  Completed: __t.unit(),
  Failed: __t.unit(),
});
export type AiGenerationStatus = __Infer<typeof AiGenerationStatus>;

export const Book = __t.object("Book", {
  id: __t.string(),
  title: __t.string(),
  author: __t.string(),
  isbn: __t.string(),
  get category() {
    return BookCategory;
  },
  publishedDate: __t.string(),
  publisher: __t.string(),
  totalCopies: __t.i32(),
  availableCopies: __t.i32(),
  get status() {
    return BookStatus;
  },
  coverUrl: __t.option(__t.string()),
  description: __t.option(__t.string()),
  location: __t.string(),
  branchId: __t.string(),
  get format() {
    return __t.array(BookFormat);
  },
  pages: __t.option(__t.i32()),
  language: __t.option(__t.string()),
  edition: __t.option(__t.string()),
  pdfData: __t.option(__t.string()),
  coverData: __t.option(__t.string()),
  rating: __t.f64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Book = __Infer<typeof Book>;

// The tagged union or sum type for the algebraic type `BookCategory`.
export const BookCategory = __t.enum("BookCategory", {
  Fiction: __t.unit(),
  NonFiction: __t.unit(),
  Technology: __t.unit(),
  Science: __t.unit(),
  History: __t.unit(),
  SelfHelp: __t.unit(),
  Academic: __t.unit(),
  Thriller: __t.unit(),
  Mystery: __t.unit(),
  Fantasy: __t.unit(),
  Biography: __t.unit(),
  Philosophy: __t.unit(),
  Art: __t.unit(),
  Romance: __t.unit(),
  Dystopian: __t.unit(),
  Journal: __t.unit(),
  Poetry: __t.unit(),
  Comics: __t.unit(),
  Other: __t.unit(),
});
export type BookCategory = __Infer<typeof BookCategory>;

// The tagged union or sum type for the algebraic type `BookFormat`.
export const BookFormat = __t.enum("BookFormat", {
  Hardcopy: __t.unit(),
  Ebook: __t.unit(),
  Audiobook: __t.unit(),
});
export type BookFormat = __Infer<typeof BookFormat>;

export const BookRating = __t.object("BookRating", {
  id: __t.string(),
  bookId: __t.string(),
  userId: __t.string(),
  rating: __t.f64(),
  createdAt: __t.string(),
});
export type BookRating = __Infer<typeof BookRating>;

// The tagged union or sum type for the algebraic type `BookStatus`.
export const BookStatus = __t.enum("BookStatus", {
  Available: __t.unit(),
  Borrowed: __t.unit(),
  Overdue: __t.unit(),
  Reserved: __t.unit(),
  Lost: __t.unit(),
});
export type BookStatus = __Infer<typeof BookStatus>;

export const BorrowRecord = __t.object("BorrowRecord", {
  id: __t.string(),
  bookId: __t.string(),
  userId: __t.string(),
  borrowDate: __t.string(),
  dueDate: __t.string(),
  returnDate: __t.option(__t.string()),
  get status() {
    return BorrowStatus;
  },
  branchId: __t.string(),
  fine: __t.option(__t.f64()),
  renewCount: __t.i32(),
});
export type BorrowRecord = __Infer<typeof BorrowRecord>;

// The tagged union or sum type for the algebraic type `BorrowStatus`.
export const BorrowStatus = __t.enum("BorrowStatus", {
  Active: __t.unit(),
  Returned: __t.unit(),
  Overdue: __t.unit(),
});
export type BorrowStatus = __Infer<typeof BorrowStatus>;

export const Branch = __t.object("Branch", {
  id: __t.string(),
  name: __t.string(),
  address: __t.string(),
  city: __t.string(),
  phone: __t.string(),
  email: __t.string(),
  manager: __t.string(),
  totalBooks: __t.i32(),
  totalMembers: __t.i32(),
  get status() {
    return BranchStatus;
  },
  openHours: __t.string(),
});
export type Branch = __Infer<typeof Branch>;

// The tagged union or sum type for the algebraic type `BranchStatus`.
export const BranchStatus = __t.enum("BranchStatus", {
  Active: __t.unit(),
  Inactive: __t.unit(),
});
export type BranchStatus = __Infer<typeof BranchStatus>;

export const LibraryUser = __t.object("LibraryUser", {
  id: __t.string(),
  clerkId: __t.string(),
  name: __t.string(),
  email: __t.string(),
  get role() {
    return UserRole;
  },
  phone: __t.option(__t.string()),
  address: __t.option(__t.string()),
  avatar: __t.option(__t.string()),
  memberSince: __t.string(),
  get membershipType() {
    return MembershipType;
  },
  borrowLimit: __t.i32(),
  bio: __t.option(__t.string()),
  registerNumber: __t.option(__t.string()),
  department: __t.option(__t.string()),
  get status() {
    return UserStatus;
  },
  createdAt: __t.timestamp(),
});
export type LibraryUser = __Infer<typeof LibraryUser>;

// The tagged union or sum type for the algebraic type `MembershipType`.
export const MembershipType = __t.enum("MembershipType", {
  Basic: __t.unit(),
  Premium: __t.unit(),
  Scholar: __t.unit(),
});
export type MembershipType = __Infer<typeof MembershipType>;

export const Notification = __t.object("Notification", {
  id: __t.string(),
  userId: __t.string(),
  get notificationType() {
    return NotificationType;
  },
  title: __t.string(),
  message: __t.string(),
  date: __t.string(),
  read: __t.bool(),
});
export type Notification = __Infer<typeof Notification>;

// The tagged union or sum type for the algebraic type `NotificationType`.
export const NotificationType = __t.enum("NotificationType", {
  Overdue: __t.unit(),
  Available: __t.unit(),
  Reminder: __t.unit(),
  System: __t.unit(),
});
export type NotificationType = __Infer<typeof NotificationType>;

// The tagged union or sum type for the algebraic type `UserRole`.
export const UserRole = __t.enum("UserRole", {
  Admin: __t.unit(),
  Librarian: __t.unit(),
  Member: __t.unit(),
});
export type UserRole = __Infer<typeof UserRole>;

// The tagged union or sum type for the algebraic type `UserStatus`.
export const UserStatus = __t.enum("UserStatus", {
  Active: __t.unit(),
  Suspended: __t.unit(),
});
export type UserStatus = __Infer<typeof UserStatus>;

