// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  BookCategory,
  BookFormat,
  BookStatus,
} from "./types";

export default {
  id: __t.string(),
  title: __t.string(),
  author: __t.string(),
  isbn: __t.string(),
  get category() {
    return BookCategory;
  },
  publishedDate: __t.string(),
  publisher: __t.string(),
  totalCopies: __t.i32(),
  availableCopies: __t.i32(),
  get status() {
    return BookStatus;
  },
  description: __t.option(__t.string()),
  location: __t.string(),
  branchId: __t.string(),
  get format() {
    return __t.array(BookFormat);
  },
  pages: __t.option(__t.i32()),
  language: __t.option(__t.string()),
  edition: __t.option(__t.string()),
  coverUrl: __t.option(__t.string()),
  pdfData: __t.option(__t.string()),
  coverData: __t.option(__t.string()),
};
